services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - my_network

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"    # MQTT protocol port
      - "9001:9001"    # WebSocket protocol port
    volumes:
      - ./config:/mosquitto/config   # Configuration files
      - ./data:/mosquitto/data       # Persistence data
      - ./log:/mosquitto/log         # Log files
    stdin_open: true
    tty: true
    networks:
      - my_network
  
  # IOT Devices
  plc:
    build:
      context: ../.
      dockerfile: deployment/Dockerfile
      args:
        IOT_PATH: app.plc
        IOT_NAME: plc_usr
        MQTT_HOST: mosquitto
        DB_HOST: postgres
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - my_network
  p_debit_rtrm:
    build:
      context: ../.
      dockerfile: deployment/Dockerfile
      args:
        IOT_PATH: app.sensor
        IOT_NAME: P_Debit_RTRTM
        MQTT_HOST: mosquitto
        DB_HOST: postgres
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - my_network

networks:
  my_network:
    driver: bridge