{
 "title": "INF6103",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pipes (Untreated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sensor_value{sensor=\"P_Debit_TRTM_In\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"P_Debit_TRTM_Out\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Untreated Tank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sensor_value{sensor=\"T_Level_TRTM\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Temperature_TRTM\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Dissolved_Oxygen_TRTM\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Turbidity_TRTM\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_PH_TRTM\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Treated Tank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sensor_value{sensor=\"T_Level_TRT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Temperature_TRT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Conductivity_TRT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Dissolved_Oxygen_TRT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_Turbidity_TRT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"T_PH_TRT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipes (Treated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sensor_value{sensor=\"P_Debit_TRTM_Out\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_value{sensor=\"P_Debit_RTRTM\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}